/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameMgr from "./newScript/GameMgr"
import BarrierMgr from "./newScript/BarrierMgr"
import GameUI from "./script/GameUI"
import GameControl from "./script/GameControl"
import EffBarrier from "./newScript/EffBarrier"
import Bullet from "./script/Bullet"
import DropBox from "./script/DropBox"
import PlayBall from "./newScript/PlayBall"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("newScript/GameMgr.js",GameMgr);
		reg("newScript/BarrierMgr.js",BarrierMgr);
		reg("script/GameUI.js",GameUI);
		reg("script/GameControl.js",GameControl);
		reg("newScript/EffBarrier.js",EffBarrier);
		reg("script/Bullet.js",Bullet);
		reg("script/DropBox.js",DropBox);
		reg("newScript/PlayBall.js",PlayBall);
    }
}
GameConfig.width = 750;
GameConfig.height = 1334;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "vertical";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "game/MainScene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
